// <auto-generated />
using System;
using EarlyInterventionCare.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EarlyInterventionCare.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261005184434_AddSubmissionReceiptWindow")]
    partial class AddSubmissionReceiptWindow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("EventId"), "ascii");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("actor_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("RequestCorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("request_correlation_id");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("resource_type");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("result");

                    b.HasKey("EventId");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_audit_time");

                    b.HasIndex("ResourceType", "ResourceId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_resource_time");

                    b.ToTable("audit_logs", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.CaseRecord", b =>
                {
                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("case_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("CaseId"), "ascii");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("CaseCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("case_code");

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('NEW', 'TO_CONTACT', 'APPOINTED', 'WAITING_FORM', 'FORM_COMPLETED', 'COMPLETED')")
                        .HasDefaultValue("NEW")
                        .HasColumnName("case_status");

                    b.Property<string>("ChildName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("child_name");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("ENUM('MALE', 'FEMALE', 'UNKNOWN')")
                        .HasColumnName("sex");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("CaseId");

                    b.HasIndex("CaseCode")
                        .IsUnique()
                        .HasDatabaseName("uq_cases_code");

                    b.ToTable("cases", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.Questionnaire", b =>
                {
                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("char(36)")
                        .HasColumnName("questionnaire_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("QuestionnaireId"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("QuestionnaireCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("questionnaire_code")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("QuestionnaireCode"), "ascii");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("QuestionnaireId");

                    b.HasIndex("QuestionnaireCode")
                        .IsUnique()
                        .HasDatabaseName("uq_questionnaires_code");

                    b.ToTable("questionnaires", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.QuestionnaireDraft", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)")
                        .HasColumnName("task_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TaskId"), "ascii");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("answers_json");

                    b.Property<DateOnly?>("FilledOn")
                        .HasColumnType("date")
                        .HasColumnName("filled_on");

                    b.Property<Guid?>("LastSavedByGrantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("last_saved_by_grant_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("LastSavedByGrantId"), "ascii");

                    b.Property<string>("Observation")
                        .HasColumnType("text")
                        .HasColumnName("observation");

                    b.Property<Guid>("QuestionnaireVersionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("questionnaire_version_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("QuestionnaireVersionId"), "ascii");

                    b.Property<string>("RespondentName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("respondent_name");

                    b.Property<ulong>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("revision");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("TaskId");

                    b.HasIndex("LastSavedByGrantId", "TaskId");

                    b.HasIndex("TaskId", "QuestionnaireVersionId");

                    b.ToTable("questionnaire_drafts", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.QuestionnaireResponse", b =>
                {
                    b.Property<Guid>("ResponseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("response_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("ResponseId"), "ascii");

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("answers_json");

                    b.Property<DateOnly>("FilledOn")
                        .HasColumnType("date")
                        .HasColumnName("filled_on");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("char(36)")
                        .HasColumnName("idempotency_key")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("IdempotencyKey"), "ascii");

                    b.Property<string>("Observation")
                        .HasColumnType("text")
                        .HasColumnName("observation");

                    b.Property<byte[]>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("payload_hash");

                    b.Property<Guid>("QuestionnaireVersionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("questionnaire_version_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("QuestionnaireVersionId"), "ascii");

                    b.Property<string>("RespondentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("respondent_name");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at_utc");

                    b.Property<Guid?>("SubmittedByGrantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("submitted_by_grant_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("SubmittedByGrantId"), "ascii");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)")
                        .HasColumnName("task_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TaskId"), "ascii");

                    b.HasKey("ResponseId");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasDatabaseName("uq_responses_task");

                    b.HasIndex("SubmittedByGrantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("uq_responses_grant_key");

                    b.HasIndex("SubmittedByGrantId", "TaskId");

                    b.HasIndex("TaskId", "QuestionnaireVersionId");

                    b.ToTable("questionnaire_responses", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.QuestionnaireTask", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)")
                        .HasColumnName("task_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TaskId"), "ascii");

                    b.Property<uint>("AssignmentRound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(1u)
                        .HasColumnName("assignment_round");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("case_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("CaseId"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("char(36)")
                        .HasColumnName("questionnaire_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("QuestionnaireId"), "ascii");

                    b.Property<Guid>("QuestionnaireVersionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("questionnaire_version_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("QuestionnaireVersionId"), "ascii");

                    b.Property<string>("RespondentRole")
                        .IsRequired()
                        .HasColumnType("ENUM('PARENT', 'TEACHER')")
                        .HasColumnName("respondent_role");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("submitted_at_utc");

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('PENDING', 'IN_PROGRESS', 'SUBMITTED', 'CANCELLED')")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("task_status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("TaskId");

                    b.HasAlternateKey("TaskId", "QuestionnaireVersionId")
                        .HasName("uq_tasks_version");

                    b.HasAlternateKey("TaskId", "CaseId", "RespondentRole")
                        .HasName("uq_tasks_scope");

                    b.HasIndex("QuestionnaireVersionId", "QuestionnaireId", "RespondentRole");

                    b.HasIndex("CaseId", "QuestionnaireId", "RespondentRole", "AssignmentRound")
                        .IsUnique()
                        .HasDatabaseName("uq_tasks_assignment");

                    b.ToTable("case_questionnaires", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.QuestionnaireVersion", b =>
                {
                    b.Property<Guid>("QuestionnaireVersionId")
                        .HasColumnType("char(36)")
                        .HasColumnName("questionnaire_version_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("QuestionnaireVersionId"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefinitionSnapshot")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("definition_snapshot");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("published_at_utc");

                    b.Property<Guid>("QuestionnaireId")
                        .HasColumnType("char(36)")
                        .HasColumnName("questionnaire_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("QuestionnaireId"), "ascii");

                    b.Property<string>("RespondentRole")
                        .IsRequired()
                        .HasColumnType("ENUM('PARENT', 'TEACHER')")
                        .HasColumnName("respondent_role");

                    b.Property<string>("ScoringDefinition")
                        .HasColumnType("json")
                        .HasColumnName("scoring_definition");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("version_number")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("VersionNumber"), "ascii");

                    b.Property<string>("VersionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('DRAFT', 'PUBLISHED', 'RETIRED')")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("version_status");

                    b.HasKey("QuestionnaireVersionId");

                    b.HasAlternateKey("QuestionnaireVersionId", "QuestionnaireId", "RespondentRole")
                        .HasName("uq_versions_type");

                    b.HasIndex("QuestionnaireId", "RespondentRole", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_versions_number");

                    b.ToTable("questionnaire_versions", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.TeacherGrant", b =>
                {
                    b.Property<Guid>("GrantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("grant_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("GrantId"), "ascii");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("case_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("CaseId"), "ascii");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("binary(32)")
                        .HasColumnName("code_hash");

                    b.Property<Guid?>("ConsentReferenceId")
                        .HasColumnType("char(36)")
                        .HasColumnName("consent_reference_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("ConsentReferenceId"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("GrantStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('ACTIVE', 'USED', 'REVOKED')")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("grant_status");

                    b.Property<bool>("IsDevelopment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_development");

                    b.Property<Guid?>("IssuedByUserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("issued_by_user_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid?>("IssuedByUserId"), "ascii");

                    b.Property<string>("RespondentRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('PARENT', 'TEACHER')")
                        .HasDefaultValue("TEACHER")
                        .HasColumnName("respondent_role");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("used_at_utc");

                    b.HasKey("GrantId");

                    b.HasAlternateKey("GrantId", "CaseId", "RespondentRole")
                        .HasName("uq_grants_scope");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("uq_grants_code_hash");

                    b.HasIndex("CaseId", "GrantStatus")
                        .HasDatabaseName("ix_grants_case_status");

                    b.ToTable("teacher_grants", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.TeacherGrantTask", b =>
                {
                    b.Property<Guid>("GrantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("grant_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("GrantId"), "ascii");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)")
                        .HasColumnName("task_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("TaskId"), "ascii");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("char(36)")
                        .HasColumnName("case_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("CaseId"), "ascii");

                    b.Property<string>("RespondentRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('PARENT', 'TEACHER')")
                        .HasDefaultValue("TEACHER")
                        .HasColumnName("respondent_role");

                    b.HasKey("GrantId", "TaskId");

                    b.HasIndex("GrantId", "CaseId", "RespondentRole");

                    b.HasIndex("TaskId", "CaseId", "RespondentRole")
                        .HasDatabaseName("ix_grant_tasks_task_scope");

                    b.ToTable("teacher_grant_tasks", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.TeacherSession", b =>
                {
                    b.Property<byte[]>("SessionHash")
                        .HasColumnType("binary(32)")
                        .HasColumnName("session_hash");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("GrantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("grant_id")
                        .UseCollation("ascii_bin");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<Guid>("GrantId"), "ascii");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<DateTime?>("ReceiptExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("receipt_expires_at_utc");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at_utc");

                    b.Property<DateTime>("SessionExpiresAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("session_expires_at_utc");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("ENUM('ACTIVE', 'REVOKED')")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("session_status");

                    b.HasKey("SessionHash");

                    b.HasIndex("GrantId", "SessionStatus")
                        .HasDatabaseName("ix_sessions_grant_status");

                    b.ToTable("teacher_sessions", (string)null);

                    MySqlEntityTypeBuilderExtensions.HasCharSet(b, "utf8mb4");
                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.QuestionnaireDraft", b =>
                {
                    b.HasOne("EarlyInterventionCare.Api.Data.Entities.TeacherGrantTask", null)
                        .WithMany()
                        .HasForeignKey("LastSavedByGrantId", "TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_drafts_grant_scope");

                    b.HasOne("EarlyInterventionCare.Api.Data.Entities.QuestionnaireTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId", "QuestionnaireVersionId")
                        .HasPrincipalKey("TaskId", "QuestionnaireVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_drafts_task_version");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.QuestionnaireResponse", b =>
                {
                    b.HasOne("EarlyInterventionCare.Api.Data.Entities.TeacherGrantTask", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByGrantId", "TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_responses_grant_scope");

                    b.HasOne("EarlyInterventionCare.Api.Data.Entities.QuestionnaireTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId", "QuestionnaireVersionId")
                        .HasPrincipalKey("TaskId", "QuestionnaireVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_responses_task_version");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.QuestionnaireTask", b =>
                {
                    b.HasOne("EarlyInterventionCare.Api.Data.Entities.CaseRecord", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_case");

                    b.HasOne("EarlyInterventionCare.Api.Data.Entities.QuestionnaireVersion", null)
                        .WithMany()
                        .HasForeignKey("QuestionnaireVersionId", "QuestionnaireId", "RespondentRole")
                        .HasPrincipalKey("QuestionnaireVersionId", "QuestionnaireId", "RespondentRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tasks_version_type");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.QuestionnaireVersion", b =>
                {
                    b.HasOne("EarlyInterventionCare.Api.Data.Entities.Questionnaire", null)
                        .WithMany()
                        .HasForeignKey("QuestionnaireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_versions_questionnaire");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.TeacherGrant", b =>
                {
                    b.HasOne("EarlyInterventionCare.Api.Data.Entities.CaseRecord", null)
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grants_case");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.TeacherGrantTask", b =>
                {
                    b.HasOne("EarlyInterventionCare.Api.Data.Entities.TeacherGrant", null)
                        .WithMany()
                        .HasForeignKey("GrantId", "CaseId", "RespondentRole")
                        .HasPrincipalKey("GrantId", "CaseId", "RespondentRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grant_tasks_grant_scope");

                    b.HasOne("EarlyInterventionCare.Api.Data.Entities.QuestionnaireTask", null)
                        .WithMany()
                        .HasForeignKey("TaskId", "CaseId", "RespondentRole")
                        .HasPrincipalKey("TaskId", "CaseId", "RespondentRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grant_tasks_task_scope");
                });

            modelBuilder.Entity("EarlyInterventionCare.Api.Data.Entities.TeacherSession", b =>
                {
                    b.HasOne("EarlyInterventionCare.Api.Data.Entities.TeacherGrant", null)
                        .WithMany()
                        .HasForeignKey("GrantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_grant");
                });
#pragma warning restore 612, 618
        }
    }
}
